# Generated by Django 4.2.3 on 2023-07-12 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='SErvice Name', max_length=100, unique=True, verbose_name='Title')),
                ('summary', models.CharField(help_text='Service summary', max_length=200, null=True, unique=True, verbose_name='Summary')),
                ('description', models.TextField(help_text='Description of Service', verbose_name='Description')),
                ('icon', models.CharField(help_text='Icon of service', max_length=50, unique=True, verbose_name='Icon')),
                ('picture', models.ImageField(height_field='height_field', max_length=110, upload_to='service/', verbose_name='Picture', width_field='width_field')),
                ('pic_height_field', models.PositiveSmallIntegerField(blank=True, editable=False, help_text="Size of Picture's height", null=True)),
                ('pic_width_field', models.PositiveSmallIntegerField(blank=True, editable=False, help_text="Size of Picture's width", null=True)),
                ('pic_alternate_text', models.CharField(help_text='Description about picture that is uploaded.', max_length=110)),
                ('banner', models.ImageField(height_field='height_field', max_length=110, upload_to='banner/', verbose_name='Banner', width_field='width_field')),
                ('banner_height_field', models.PositiveSmallIntegerField(blank=True, editable=False, help_text="Size of Picture's height", null=True)),
                ('banner_width_field', models.PositiveSmallIntegerField(blank=True, editable=False, help_text="Size of Picture's width", null=True)),
                ('banner_alternate_text', models.CharField(help_text='Description about banner that is uploaded.', max_length=110)),
                ('created', models.DateTimeField(auto_now_add=True, help_text='auto insertion')),
                ('modified', models.DateTimeField(auto_now=True, help_text='auto mification')),
            ],
        ),
    ]
